Friend Module GameState
    Friend Const ActionMenu = "ActionMenu"
    Friend Const Navigation = "Navigation"
    Friend Const Dead = "Dead"
    Friend Const Drop = "Drop"
    Friend Const Combat = "Combat"
    Friend Const Run = "Run"
    Friend Const Attack = "Attack"
    Friend Const Message = "Message"
    Friend Const Inventory = "Inventory"
    Friend Const Status = "Status"
    Friend Const Ground = "Ground"
    Friend Const Take = "Take"
    Friend Const InventoryDetail = "InventoryDetail"
End Module
